name: test
run-name: test
on: [push]
jobs:
  j1:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - name: step1
        uses:  actions/checkout@v4
      - run:  echo "::debug::linux is good"
      - run: crystal aa.cr
      - run: ls -lht