name: zerotier
run-name: test
on:
    workflow_dispatch:
      inputs:
        server:
          description: "server info"
          required: true
          type: string
        timeout-minutes:
          description:  "timeout"
          required: true
          type: number
          default: 15
jobs:
  j1:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(inputs.timeout-minutes) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - name: setup
        run: |
              wget https://github.com/v2ray/dist/raw/refs/heads/master/v2ray-linux-64.zip
              unzip v2ray-linux-64.zip
              ./v2ray run -c server.json